/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InvoicesPageImport } from './routes/invoicesPage'
import { Route as InvoiceHistoryImport } from './routes/invoiceHistory'
import { Route as CreateInvoiceImport } from './routes/createInvoice'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as HistoryIdImport } from './routes/history.$id'

// Create/Update Routes

const InvoicesPageRoute = InvoicesPageImport.update({
  id: '/invoicesPage',
  path: '/invoicesPage',
  getParentRoute: () => rootRoute,
} as any)

const InvoiceHistoryRoute = InvoiceHistoryImport.update({
  id: '/invoiceHistory',
  path: '/invoiceHistory',
  getParentRoute: () => rootRoute,
} as any)

const CreateInvoiceRoute = CreateInvoiceImport.update({
  id: '/createInvoice',
  path: '/createInvoice',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIdRoute = HistoryIdImport.update({
  id: '/history/$id',
  path: '/history/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/createInvoice': {
      id: '/createInvoice'
      path: '/createInvoice'
      fullPath: '/createInvoice'
      preLoaderRoute: typeof CreateInvoiceImport
      parentRoute: typeof rootRoute
    }
    '/invoiceHistory': {
      id: '/invoiceHistory'
      path: '/invoiceHistory'
      fullPath: '/invoiceHistory'
      preLoaderRoute: typeof InvoiceHistoryImport
      parentRoute: typeof rootRoute
    }
    '/invoicesPage': {
      id: '/invoicesPage'
      path: '/invoicesPage'
      fullPath: '/invoicesPage'
      preLoaderRoute: typeof InvoicesPageImport
      parentRoute: typeof rootRoute
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/history/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/createInvoice': typeof CreateInvoiceRoute
  '/invoiceHistory': typeof InvoiceHistoryRoute
  '/invoicesPage': typeof InvoicesPageRoute
  '/history/$id': typeof HistoryIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/createInvoice': typeof CreateInvoiceRoute
  '/invoiceHistory': typeof InvoiceHistoryRoute
  '/invoicesPage': typeof InvoicesPageRoute
  '/history/$id': typeof HistoryIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/createInvoice': typeof CreateInvoiceRoute
  '/invoiceHistory': typeof InvoiceHistoryRoute
  '/invoicesPage': typeof InvoicesPageRoute
  '/history/$id': typeof HistoryIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/createInvoice'
    | '/invoiceHistory'
    | '/invoicesPage'
    | '/history/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/createInvoice'
    | '/invoiceHistory'
    | '/invoicesPage'
    | '/history/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/createInvoice'
    | '/invoiceHistory'
    | '/invoicesPage'
    | '/history/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateInvoiceRoute: typeof CreateInvoiceRoute
  InvoiceHistoryRoute: typeof InvoiceHistoryRoute
  InvoicesPageRoute: typeof InvoicesPageRoute
  HistoryIdRoute: typeof HistoryIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateInvoiceRoute: CreateInvoiceRoute,
  InvoiceHistoryRoute: InvoiceHistoryRoute,
  InvoicesPageRoute: InvoicesPageRoute,
  HistoryIdRoute: HistoryIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/createInvoice",
        "/invoiceHistory",
        "/invoicesPage",
        "/history/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/createInvoice": {
      "filePath": "createInvoice.tsx"
    },
    "/invoiceHistory": {
      "filePath": "invoiceHistory.tsx"
    },
    "/invoicesPage": {
      "filePath": "invoicesPage.tsx"
    },
    "/history/$id": {
      "filePath": "history.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
